name = "Countdown"
usage = "Countdown from start number to end number."
usage_examples = ["Countdown from 10 to 0", "Countdown from 5 to 0"]
gpt_mode = "speed"
execution_mode = "aiconsole.core.chat.execution_modes.example_countdown:execution_mode"
default_status = "enabled"
system = """
"""
